// This file was generated by counterfeiter
package cowbullfakes

import (
	"sync"

	"github.com/Bo0mer/cowbull"
	"github.com/Bo0mer/cowbull/game"
)

type FakeGamer struct {
	GameStub        func(game.Thinker, game.Guesser) (*game.Game, error)
	gameMutex       sync.RWMutex
	gameArgsForCall []struct {
		arg1 game.Thinker
		arg2 game.Guesser
	}
	gameReturns struct {
		result1 *game.Game
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGamer) Game(arg1 game.Thinker, arg2 game.Guesser) (*game.Game, error) {
	fake.gameMutex.Lock()
	fake.gameArgsForCall = append(fake.gameArgsForCall, struct {
		arg1 game.Thinker
		arg2 game.Guesser
	}{arg1, arg2})
	fake.recordInvocation("Game", []interface{}{arg1, arg2})
	fake.gameMutex.Unlock()
	if fake.GameStub != nil {
		return fake.GameStub(arg1, arg2)
	} else {
		return fake.gameReturns.result1, fake.gameReturns.result2
	}
}

func (fake *FakeGamer) GameCallCount() int {
	fake.gameMutex.RLock()
	defer fake.gameMutex.RUnlock()
	return len(fake.gameArgsForCall)
}

func (fake *FakeGamer) GameArgsForCall(i int) (game.Thinker, game.Guesser) {
	fake.gameMutex.RLock()
	defer fake.gameMutex.RUnlock()
	return fake.gameArgsForCall[i].arg1, fake.gameArgsForCall[i].arg2
}

func (fake *FakeGamer) GameReturns(result1 *game.Game, result2 error) {
	fake.GameStub = nil
	fake.gameReturns = struct {
		result1 *game.Game
		result2 error
	}{result1, result2}
}

func (fake *FakeGamer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.gameMutex.RLock()
	defer fake.gameMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeGamer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cowbull.Gamer = new(FakeGamer)
